// Copyright (C) 2002-2013 Nikolaus Gebhardt
// This file is part of the "Irrlicht Engine" for the D programming language.
// For conditions of distribution and use, see copyright notice in irrlicht.d module.
module irrlicht.IRandomizer;

/// Interface for generating random numbers
interface IRandomizer 
{
	/// resets the randomizer
	/** 
	* Params:
	* value = Initialization value (seed) 
	*/
	void reset(int value=0x0f0f0f0f);

	/// generates a pseudo random number in the range 0..randMax()
	int rand() const;

	/// generates a pseudo random number in the range 0..1
	float frand() const;

	/// get maxmimum number generated by rand()
	int randMax() const;
}